---
title: Final Considerations
author: Luca Baggi
date: '2021-01-17'
slug: []
categories: []
tags: []
---

The aim of this analysis is to display some machine learning techniques, without expecting to be exhaustive. Notably, there is one serious shortcoming: models should not include geographical coordinates as independent variables. Instead, a grid should have made out of these and observations assigned to each. In this way, more patterns may have been discovered.

Given this information, we could have also created ideal paths for each trip, using data from one cell to another. This wouldn't have improved the predictive models, but had an impact on clustering and identifying hotspots locations (such as stations).

One great limitation was hardware. `Tidymodels` proved useful, albeit overly complicated at times: what'ss the need of `prep()`-ing a recipe and separately `juice()` the training set and `bake()` the test one? Also, it seems there is not too much support for unsupervised learning.

To implement better and more meaningful visualisations, the following will need implementation:

1. Facet histograms of distance and duration for each neighbourhood
2. More maps, perhaps with flows

The last point will need a greater understanding of R geographical libraries, which are more fragmented with respect to Python. These would also be useful in making the grid.

Finally, a time-series predictive model would be great to conclude the analysis.